const ActionTypes = {
    "ROLL_DICE": "ROLL_DICE",
    "MOVE_PIECE": "MOVE_PIECE",
    "GENERATE_CANDIDATE_MOVE": "GENERATE_CANDIDATE_MOVE",
    "TOGGLE_DICE": "TOGGLE_DICE",
    "SCORE": "SCORE",
    "CAPTURE": "CAPTURE",
    "DECREMENT_RED_STACK": "DECREMENT_RED_STACK",
    "DECREMENT_BLUE_STACK": "DECREMENT_BLUE_STACK",
    "CLEAR_CANDIDATE_MOVE" : "CLEAR_CANDIDATE_MOVE",
    "TOGGLE_TUTORIAL" : "TOGGLE_TUTORIAL"
}

export default ActionTypes;